### ISSUE TITLE
milestone deliverable links

### ISSUE THREAD

**Issue by fanux** [bytepayment/bytepay#2]
| Number | Deliverable | Specification |
| ------------- | ------------- | ------------- |
| 0a. | License | Apache 2.0 |
| 0b. | Documentation | Dotpay user guide, workflow, and what is dotpay. |
| 0c. | Testing Guide | We will provide uni test for user management and recharge management modules(70% cover), the two module UI test report |
| 0d. | Docker | We will provide Dockerfile and docker image to run the website in one command line |
| 1. | User management, create an polkadot account for each developer | We will provide login function, you can login our website using github, and we will create an polkadot account for each user by default |
| 2. | Repo & webhook management| We will fetch your github repo list, so you can active the repo you want integrate with polkadot, the webhook module will listen the pay event and tigger transform module to pay developer DOT |
| 3. | Address binding | Develop using github issue comment to bind there polkadot address. `/dotpay bind [address]` |
| 4. | Recharge management | Recharge DOT to your platform account |
| 5. | Transfer ink! contract| We will provide an tested ink! contract on Substrate Smart Contracts Node, provide transfer limit, witelist and transfer function. The platform will integrate the contract when the Polkadot mainnet contract para chain is available. |

**Comment by fanux** [comment]
| Number | Deliverable | Specification |
| ------------- | ------------- | ------------- |
| 0a. | License | Apache 2.0 |
| 0b. | Documentation | We will provide docs about how to create a task, how to tigger the payment, and how to withdraw |
| 0c. | Testing Guide | We will provide uni test for task,transfer,informal,withdraw modules(70% cover), and UI test report |
| 0d. | Docker | We will provide Dockerfile and docker image to run the website in one command line, and you can to test those modules |
| 1. | Task management | Create a paid task by comment an issue, it will trigger the create task event though the webhook, and webhook server will save the task and show it on our page, when developer complete the task, will tigger transfer module to pay the developer |
| 2. | Tansfer module | Trigger a payment by comment an issue, like `/pay Bob 10DOT`, the DOT will transfer to developer platform account |
| 3. | Withdraw module | Withdraw the DOT from our platform to developer own wallet, if developer bind it own address, payment will transfer to the account directly |
| 4. | Informal | Developer will receive the event, tell him how to withdraw DOT in our platform, robot will send Bob email and comment the issue |

**Comment by sulnong** [comment]
1. Visit Our Online Project
[Bytepay](https://bytepay.online)
2. Docker
`docker run --rm -p 80:80 sulnong/bytepay:app`
Then open in your [(http:bytepay.local-dev.host](http:bytepay.local-dev.host)
3. Test
`docker run --rm sulnong/bytepay:test`
