### ISSUE TITLE
开发者未登录过bytepay不影响收款

### ISSUE THREAD

**Issue by AdaLam7** [bytepayment/bytepay#6]
给开发者创建地址不依赖开发者必须登录。

可以登陆的时候再绑定。

这样做的好处是开发者一开始不需要登录bytepay，只在提现的时候才需要。以降低门槛。

因为没什么事就让开发者登陆通常动力不足。但是dot已经在开发者的账户了去提现肯定就很有动力了。

还有个原因是开发者没有登陆就转账失败多了这次失败不太友好。

**Comment by AdaLam7** [comment]
![image](https://user-images.githubusercontent.com/94216827/151497865-64b9d9a7-013a-4e81-aaf7-27fd8fa418e3.png)

Can't `go ahead`

**Comment by AdaLam7** [comment]
![image](https://user-images.githubusercontent.com/94216827/151497983-5953ed14-7ddd-4254-ab47-cec9b835b59a.png)
dot < 0.1 不显示

**Comment by AdaLam7** [comment]
![image](https://user-images.githubusercontent.com/94216827/151498336-16c639ca-7a82-4c7f-b86c-071b209d592b.png)

task在右边显示，那左边的tab页可以直接删了

**Comment by AdaLam7** [comment]
![image](https://user-images.githubusercontent.com/94216827/151500293-a07eab57-58cc-43d5-9715-6ae7aab63625.png)
bind指令似乎不起作用
![image](https://user-images.githubusercontent.com/94216827/151500347-5d4a1f6e-c493-41db-8f3c-980773ef0991.png)

**Comment by AdaLam7** [comment]
https://github.com/fanux/adidoks/issues/2

**Comment by sulnong** [comment]
> 给开发者创建地址不依赖开发者必须登录。
> 
> 可以登陆的时候再绑定。
> 
> 这样做的好处是开发者一开始不需要登录bytepay，只在提现的时候才需要。以降低门槛。
> 
> 因为没什么事就让开发者登陆通常动力不足。但是dot已经在开发者的账户了去提现肯定就很有动力了。
> 
> 还有个原因是开发者没有登陆就转账失败多了这次失败不太友好。


确实，是否登录bytepay只影响能否获取授权绑定仓库，添加webhooks这一项操作。

1. **Apply**
我们在issue comment 的 payload （`sender` filed）中可以拿到用户的github账户公开信息, 所以在开发者申请任务的时候
我们就给他生成波卡账户，待开发者登录bytepay的时候进行同步

2. **Pay**
在owner 触发 `/bytepay pay`的时候
- 若开发者未绑定自己地址，则直接支付至我们生成的波卡账户，提醒 开发者去bytepay 提现
- 若开发者已绑定自己地址，则直接支付至开发者绑定地址

3. **Bind**
- 若开发者未绑定过，则使用绑定指令`/bytepay bind address` 进行绑定
- 若开发者已绑定，则提醒开发者去bytepay进行更改（也可以做成直接覆盖原绑定地址）

以上流程就可以做到：

开发者只有在提现和更改已绑定地址的情况下才需要去bytepay

其余场景对bytepay是无感知的

**Comment by sulnong** [comment]
> ![image](https://user-images.githubusercontent.com/94216827/151498336-16c639ca-7a82-4c7f-b86c-071b209d592b.png)
> 
> task在右边显示，那左边的tab页可以直接删了

页面已修改，developer task与author task保持一致UI
